name: Daily OurWeather
on: [ push ]

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Dowload requirments
        run: pip install -r requirements.txt
      - name: Run App
        run: python app.py